name: CI-CD
  
on:
  push:
    branches: ["main"]
  workflow_dispatch:      

jobs:
  CI: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
    - name: Efetuar login no docker
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Construir e publicar a imagem
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          tiagovalentimbarreto/kube-news:v-${{ github.run_number }}
          tiagovalentimbarreto/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
    - name: Autenticar na AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Configurar kubeconfig
      run: echo "Configurar o kubeconfig"
    - name: Aplicar deploy
      run: echo "Executar kubectl apply"
    
      
